using System;
using Roblox.Datatypes;

namespace Roblox.Instances;

public class EditableMesh : Object
{
    // Methods
    public long AddBone(System.Collections.Generic.Dictionary<string, object> boneProperties) => default!;
    public long AddColor(Color3 color, float alpha) => default!;
    public long AddFace(object[]? vertexIds) => default!;
    public long AddNormal(object? normal) => default!;
    public long AddTriangle(long vertexId0, long vertexId1, long vertexId2) => default!;
    public long AddUV(Vector2 uv) => default!;
    public long AddVertex(Vector3 p) => default!;
    public object Destroy() => null!;
    public object[] FindClosestPointOnSurface(Vector3 point) => default!;
    public long FindClosestVertex(Vector3 toThisPoint) => default!;
    public object[] FindVerticesWithinSphere(Vector3 center, float radius) => default!;
    public object[] GetAdjacentFaces(long faceId) => default!;
    public object[] GetAdjacentVertices(long vertexId) => default!;
    public long GetBoneByName(string? boneName) => default!;
    public CFrame GetBoneCFrame(long boneId) => default!;
    public bool GetBoneIsVirtual(long boneId) => default!;
    public string GetBoneName(long boneId) => default!;
    public long GetBoneParent(long boneId) => default!;
    public object[] GetBones() => default!;
    public Vector3 GetCenter() => default!;
    public object GetColor(long colorId) => null!;
    public object GetColorAlpha(long colorId) => null!;
    public object[] GetColors() => default!;
    public object[] GetFaceColors(long faceId) => default!;
    public object[] GetFaceNormals(long faceId) => default!;
    public object[] GetFaceUVs(long faceId) => default!;
    public object[] GetFaceVertices(long faceId) => default!;
    public object[] GetFaces() => default!;
    public object[] GetFacesWithColor(long colorId) => default!;
    public object[] GetFacesWithNormal(long normalId) => default!;
    public object[] GetFacesWithUV(long uvId) => default!;
    public object[] GetFacsCorrectivePose(object[]? actions) => default!;
    public object[] GetFacsCorrectivePoses() => default!;
    public object[] GetFacsPose(object? action) => default!;
    public object[] GetFacsPoses() => default!;
    public object GetNormal(long normalId) => null!;
    public object[] GetNormals() => default!;
    public Vector3 GetPosition(long vertexId) => default!;
    public Vector3 GetSize() => default!;
    public object GetUV(long uvId) => null!;
    public object[] GetUVs() => default!;
    public object[] GetVertexBoneWeights(long vertexId) => default!;
    public object[] GetVertexBones(long vertexId) => default!;
    public object[] GetVertexColors(long vertexId) => default!;
    public long GetVertexFaceColor(long vertexId, long faceId) => default!;
    public long GetVertexFaceNormal(long vertexId, long faceId) => default!;
    public long GetVertexFaceUV(long vertexId, long faceId) => default!;
    public object[] GetVertexFaces(long vertexId) => default!;
    public object[] GetVertexNormals(long vertexId) => default!;
    public object[] GetVertexUVs(long vertexId) => default!;
    public object[] GetVertices() => default!;
    public object[] GetVerticesWithColor(long colorId) => default!;
    public object[] GetVerticesWithNormal(long normalId) => default!;
    public object[] GetVerticesWithUV(long uvId) => default!;
    public string IdDebugString(long id) => default!;
    public object MergeVertices(float mergeTolerance) => null!;
    public object[] RaycastLocal(Vector3 origin, Vector3 direction) => default!;
    public object RemoveBone(long boneId) => null!;
    public object RemoveFace(long faceId) => null!;
    public object[] RemoveUnused() => default!;
    public object ResetNormal(long normalId) => null!;
    public object SetBoneCFrame(long boneId, CFrame cframe) => null!;
    public object SetBoneIsVirtual(long boneId, bool @virtual) => null!;
    public object SetBoneName(long boneId, string? name) => null!;
    public object SetBoneParent(long boneId, long parentBoneId) => null!;
    public object SetColor(long colorId, Color3 color) => null!;
    public object SetColorAlpha(long colorId, float alpha) => null!;
    public object SetFaceColors(long faceId, object[]? ids) => null!;
    public object SetFaceNormals(long faceId, object[]? ids) => null!;
    public object SetFaceUVs(long faceId, object[]? ids) => null!;
    public object SetFaceVertices(long faceId, object[]? ids) => null!;
    public object SetFacsBonePose(object? action, long boneId, CFrame cframe) => null!;
    public object SetFacsCorrectivePose(object[]? actions, object[]? boneIds, object[]? cframes) => null!;
    public object SetFacsPose(object? action, object[]? boneIds, object[]? cframes) => null!;
    public object SetNormal(long normalId, Vector3 normal) => null!;
    public object SetPosition(long vertexId, Vector3 p) => null!;
    public object SetUV(long uvId, Vector2 uv) => null!;
    public object SetVertexBoneWeights(long vertexId, object[]? boneWeights) => null!;
    public object SetVertexBones(long vertexId, object[]? boneIDs) => null!;
    public object SetVertexFaceColor(long vertexId, long faceId, long colorId) => null!;
    public object SetVertexFaceNormal(long vertexId, long faceId, long normalId) => null!;
    public object SetVertexFaceUV(long vertexId, long faceId, long uvId) => null!;
    public object Triangulate() => null!;

}
